### ISSUE TITLE
finish dissertation

### ISSUE THREAD

**Issue by leafi** [DiscoBizzle/Ghost-Simulator#4]

**Comment by karnival** [comment]
Did that back in May.

**Comment by leafi** [comment]
Sorry, which commit did that come in with? I must have missed it.

**Comment by karnival** [comment]
[c.f.](https://code.google.com/p/go/source/detail?name=b66d0bf8da3e&r=f6182e5abf5eb0c762dddbb18f8854b7e350eaeb)
