### ISSUE TITLE
'Ooga booga' mechanic

### ISSUE THREAD

**Issue by leafi** [DiscoBizzle/Ghost-Simulator#9]
I've never understood the ooga booga mechanic.

As I understand it, you press the button to harvest fear from someone near who is scared.
- Does this mean you shouldn't be rewarded for pushing the victim through some sort of rube goldberg-eqsue chain of events, just because you cannot be near them at the critical point?
- Is no auto-harvesting intended to prevent cheesing the game? What's to stop someone from just spamming the button?
- We do have a problem with characters just being freaked out regularly by all sorts of banal shit. I think this'll become more solvable further in development. though.
- How does one 'harvest fear'? What does this mean in the context of the game?

**Comment by MartinHowarth** [comment]
Harvest fear == when character is ooga booga'd

**Comment by leafi** [comment]
yes thank you for that

**Comment by leafi** [comment]
jon has convinced me of the value of this. as a fyi i think we should have being able to right-click on peeps as a thing... i'm not sure there's value in having to be proximate to the dude in order to gather fear.
